src/Entity/Farmer.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\FarmerRepository")
 */
class Farmer
{
    public function __toString()
    {
        return $this->farmName;
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre adresse.")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner le nom de votre ferme.")
     */
    private $farmName;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $farmDescription;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre numéro de téléphone.")
     * @Assert\Regex(pattern="/[0-9]{10}/", message="Votre numéro de téléphone n'est pas valide.")
     */
    private $phone;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"}, fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\Valid()
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductFarmer", mappedBy="farmer", orphanRemoval=true)
     */
    private $productFarmers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Consumer", inversedBy="farmers")
     */
    private $consumer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photoProfil;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photoFarm;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="farmer", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $schedule;

    /**
     * @ORM\Column(type="float", scale=8, precision=10, nullable=true)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=8, precision=11, nullable=true)
     */
    private $lng;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $CountView;

    public function __construct()
    {
        $this->productFarmers = new ArrayCollection();
        $this->consumer = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->user = new User();
    }

    /**
     * Calculate the sum of the scores
     * @return float|int
     */
    public function getAverageScore()
    {
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);
        if (count($this->comments) > 0) return $sum / count ($this->comments);
        return 0;
    }

    /**
     * Allows to retrieve an author's comment about a farm
     * @param \App\Entity\User $author
     * @return \App\Entity\Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach($this->comments as $comment)
        {
            if($comment->getAuthor() == $author)
                return $comment;
        }
        return null;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode($postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getFarmName(): ?string
    {
        return $this->farmName;
    }

    public function setFarmName(string $farmName): self
    {
        $this->farmName = $farmName;

        return $this;
    }

    public function getSlug() :string
    {
        return (new Slugify())->slugify($this->getFarmName());

    }

    public function getFarmDescription(): ?string
    {
        return $this->farmDescription;
    }

    public function setFarmDescription(?string $farmDescription): self
    {
        $this->farmDescription = $farmDescription;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|ProductFarmer[]
     */
    public function getProductFarmers(): Collection
    {
        return $this->productFarmers;
    }

    public function addProductFarmer(ProductFarmer $productFarmer): self
    {
        if (!$this->productFarmers->contains($productFarmer)) {
            $this->productFarmers[] = $productFarmer;
            $productFarmer->setFarmer($this);
        }

        return $this;
    }

    public function removeProductFarmer(ProductFarmer $productFarmer): self
    {
        if ($this->productFarmers->contains($productFarmer)) {
            $this->productFarmers->removeElement($productFarmer);
            // set the owning side to null (unless already changed)
            if ($productFarmer->getFarmer() === $this) {
                $productFarmer->setFarmer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Consumer[]
     */
    public function getConsumer(): Collection
    {
        return $this->consumer;
    }

    public function addConsumer(Consumer $consumer): self
    {
        if (!$this->consumer->contains($consumer)) {
            $this->consumer[] = $consumer;
        }

        return $this;
    }

    public function removeConsumer(Consumer $consumer): self
    {
        if ($this->consumer->contains($consumer)) {
            $this->consumer->removeElement($consumer);
        }

        return $this;
    }

    public function setCreateAt(\DateTime $param)
    {
    }

    public function getPassword()
    {
    }

    public function getPhotoProfil()
    {
        return $this->photoProfil;
    }

    public function setPhotoProfil($photoProfil): self
    {
        $this->photoProfil = $photoProfil;

        return $this;
    }

    public function getPhotoFarm(): ?string
    {
        return $this->photoFarm;
    }

    public function setPhotoFarm(?string $photoFarm): self
    {
        $this->photoFarm = $photoFarm;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setFarmer($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getFarmer() === $this) {
                $comment->setFarmer(null);
            }
        }

        return $this;
    }

    public function getSchedule(): ?string
    {
        return $this->schedule;
    }

    public function setSchedule(?string $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

    public function getCountView(): ?int
    {
        return $this->CountView;
    }

    public function setCountView(?int $CountView): self
    {
        $this->CountView = $CountView;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Un autre utilisateur possède déjà cette adresse email !")
 */
class User implements UserInterface
{
    public function __construct()
    {
        $this->createAt = new \DateTime('now');
        $this->comments = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
    }

    public function __toString()
    {
        return (string) $this->getId();
    }
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez rentrer un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @var
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas correctement confirmé votre mot de passe!")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    private $oldPassword;

    private $newPassword;

    private $confirmPassword;

    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirmPassword;
    }

    /**
     * @param mixed $confirmPassword
     */
    public function setConfirmPassword($confirmPassword): void
    {
        $this->confirmPassword = $confirmPassword;
    }

    /**
     * @return mixed
     */
    public function getOldPassword()
    {
        return $this->oldPassword;
    }

    /**
     * @param mixed $oldPassword
     */
    public function setOldPassword($oldPassword): void
    {
        $this->oldPassword = $oldPassword;
    }

    /**
     * @return mixed
     */
    public function getNewPassword()
    {
        return $this->newPassword;
    }

    /**
     * @param mixed $newPassword
     */
    public function setNewPassword($newPassword): void
    {
        $this->newPassword = $newPassword;
    }




    /**
     * Permet d inititaliser le slug,si je n ai pas de slug
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     *
     * @return void
     */



    public function initializeSlug() {
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->getFullName());
        }
    }

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }


    public function getRoles(){

    //cette fonction est appele par le composant de securite de symfony! elle doit renvoyer la liste des roles.
    //La fonction MAP permet de boucler sur le tableau ARRAYCOLLECTION et va renvoyer un tableau avec les elements transformer.

        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';
        return $roles;
    }


    public function getSalt(){}


    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials(){}

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

}

templates/adminLayout.html.twig
<!DOCTYPE html>
<html>
<title>Vente à la ferme</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel='shortcut icon' href="assets/images/farmer.png" type="image/ico"/>

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!--[if lt IE 9]>
<script src="https://code.highcharts.com/modules/oldie.js"></script>
<![endif]-->

{{ encore_entry_link_tags('css-admin') }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="https://code.highcharts.com/highcharts.js"></script>



<title>{% block title %}Welcome!{% endblock %}</title>

<style>
    html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

<body class="w3-light-grey">
{% block navbar %}{% endblock %}

{% block body %}{% endblock %}
{% block javascripts %}{% endblock %}

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>

{{ encore_entry_script_tags('js-admin') }}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

</body>
</html>

templates/beta.html.twig
{% extends 'base.html.twig' %}

{% block navbar %}
    {% include 'consumer/navbar.html.twig' %}
{% endblock %}

{% block content %}

    <section style="padding-top: 35px">

        <div class="container">

            <h3 style="text-align: center; padding-bottom: 20px;">Nos fermiers</h3>

            <div class="row">

                <div class="col-md-6">
                    {% for farmer in farmers %}
                    <div style="padding-bottom: 20px;" class="col-md-6">
                        <div style="padding-bottom: 20px;" class="featured-blog-box">
                            <div class="featured-img">
                                <img alt="" src="{{ farmer.photoFarm }}">
                                <div class="featured-lable-blog">
                                    <p class="admin-lable">
                                        <i class="icofont icofont-user-alt-7"></i> {{ farmer.user.fullName }}
                                    </p>

                                    <p class="blog-date">
                                        <i class="icofont icofont-ui-calendar"></i> {{ (farmer.user.createAt | date("d.m.Y") ) }}
                                    </p>
                                    <div class="clearfix"></div>
                                </div>
                            </div>

                            <a href="{{ path('farm_show', {id: farmer.id, slug: farmer.slug}) }}"
                               class="featured-data">
                                <div class="blog-title">{{ farmer.farmName }}</div>
                                <div class="blog-description">
                                    {{ farmer.farmDescription [:90] ~ '...' }}
                                </div>
                            </a>
                            <div class="blog-description text-center">
                                {% if farmer.comments | length > 0 %}
                                    <div style="padding-bottom:10px">
                                        Évaluation : {% include 'part/_rating.html.twig' with {'rating': farmer.averageScore} %}
                                    </div>

                                {% else %}
                                    <div style="color: orangered; padding-bottom: 10px;">
                                        Aucune Évaluation
                                    </div>
                                {% endif %}

                                <button href="#sectionMap" id="mapButton" class="btn btn-success btn btn-block" onclick="changeMarkerPos({{ farmer.lat }}, {{ farmer.lng }}); document.documentElement.scrollTop = 0"><i class="fas fa-map-marker-alt"></i> Localiser</button>
                            </div>

                        </div>
                    </div>

                    {% endfor %}
                </div>

                <div class="col-md-6">
                    <div style="height: 500px" class="map" id="map"></div>
                </div>


                <div class="col-md-6 text-center">

                    <!-- Barre de recherche  -->
                    <div class="blog-sidebar" style="padding: 60px 0 60px 0;">
                        <div class="side-bar-title">
                            Recherche
                        </div>
                        <form action="{{ path('consumer') }}" method="post">
                            <div class="input-group subscribe-group">
                                <input class="form-control" name="choice" placeholder="Lieux, adresse, produits" type="text">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class="input-group-btn">Recherche</span>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <!-- fin barre de recherche -->

                    <!-- catagory -->
                    <div class="blog-sidebar">
                        <div class="side-bar-title">
                            Filtrer par catégories
                        </div>
                        <ul class="catagory-list">
                            {% for category in categories %}
                                <li>
                                    <a href="{{ path('consumer', { 'id': category.id}) }}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- end catagory -->


                </div>
            </div>





            <div class="row justify-content-center">
                <div class="col-3 text-center">
                    {{ knp_pagination_render(farmers) }}
                </div>
            </div>

        </div>
    </section>

    <script type="text/javascript">

        let new_lat = 45.764042; // ici les latitude de l'user.
        let new_lng = 4.835659; // ici les longitude de l'user.

        let map;
        let marker;
        let infowindow;
        let link = "http://127.0.0.1:8000/consumer/farm/";


        function initMap() {

            let locations = [
                {% for farmer in farmers %}
                ["{{ farmer.farmName }}", {{ farmer.lat }}, {{ farmer.lng }}, {{ farmer.id }}, "{{ farmer.farmDescription }}", {{ farmer.id }}, "{{ farmer.slug }}"],
                {% endfor %}
            ];

            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 10,
                center: new google.maps.LatLng(new_lat, new_lng),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });

            infowindow = new google.maps.InfoWindow();

            for (i = 0; i < locations.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                    animation: google.maps.Animation.DROP,
                    map: map
                });

                let content = '<div> <h4>' + locations[i][0] + '</h4>' + '<p>' + locations[i][4] + '</p><br/> <br/> <a href="' + link + locations[i][5] + '-' + locations[i][6] + '">Fiche de la ferme</a></div>';

                google.maps.event.addListener(marker, 'click', (function (marker, i) {
                    return function () {
                        infowindow.setContent(content);
                        infowindow.open(map, marker);
                    }
                })(marker, i));
            }

        }

        function changeMarkerPos(lat, lon) {
            let myLatLng = new google.maps.LatLng(lat, lon);
            marker.setPosition(myLatLng);
            map.setZoom(12);
            map.panTo(myLatLng);

        }

    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJMqSZgwvVasqXTm2FbQ-MlbM7O55xPl0&callback=initMap">
    </script>


{% endblock %}

templates/sideBar.html.twig
<div class="demos">
    <div class="demos-inner">

        <a href="#" id="demos-toggle" class="theme-setting event">
            <i class="fas fa-star"></i>
        </a>

        <div class="demo-header">
            <span style="font-size: 188%; color: #2C2B41;">
            <i class="fas fa-star"></i>
            </span>
        </div>

        {% if app.user and is_granted('ROLE_CONSUMER') %}
        <div class="demo-pages">
            <h4 class="text-center">Mes Fermes favorites !</h4>


            {% if followedFarmers is defined %}

            <p class="text-center margin-b-30">Accéder a vos fermes favorites!</p>

            {% for followedFarmer in followedFarmers %}

                <a href="{{ path('farm_show', {id: followedFarmer.id, slug: followedFarmer.slug}) }}" class="featured-data">
                    <div class="page-footer">
                        {{ followedFarmer.farmName }}
                    </div>
                    {% if followedFarmer.photoFarm is null %}
                        <img src="/assets/images/farm.jpg" class=" text-center" alt="photo farm" style="width: 100%; height: 125px">
                    {% else %}
                    <img src="/uploads/{{ followedFarmer.photoFarm }}" class=" text-center" alt="photo farm" style="width: 100%; height: 125px">
                    {% endif %}
                </a>
            {% endfor %}
        </div>

        {% endif %}

        {% else %}

        <div class="col col-md-12">
            <div class="box-contant section-title text-center ">

                <h4 class="text-center" >Mes Fermes favorites !</h4>

                <p class="text-center margin-b-30">Pour pouvoir ajouter des fermes ou accéder à vos favoris , veuillez-vous connecter !</p>


                <form action="{{ path('account_login') }}">
                    <button type="submit" class="btn btn-theme margin-t-10" onclick="window.location.href{{ path('account_login') }}">Commencer</button>
                </form>
            </div>
        </div>
{% endif %}